# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppcm_pgcd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ppcm import ppcm, pgcd
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PPCM_PGCD(object):
    def setupUi(self, PPCM_PGCD):
        PPCM_PGCD.setObjectName("PPCM_PGCD")
        PPCM_PGCD.resize(500, 700)
        PPCM_PGCD.setStyleSheet("background-color: rgb(255, 171, 1);")
        self.centralwidget = QtWidgets.QWidget(PPCM_PGCD)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 67, 17))
        self.label_4.setObjectName("label_4")
        self.a = QtWidgets.QLineEdit(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(130, 50, 181, 25))
        self.a.setStyleSheet("\n"
"selection-color: rgb(255, 171, 1);")
        self.a.setObjectName("a")
        self.b = QtWidgets.QLineEdit(self.centralwidget)
        self.b.setGeometry(QtCore.QRect(130, 100, 181, 25))
        self.b.setObjectName("b")
        self.r_ppcm = QtWidgets.QLineEdit(self.centralwidget)
        self.r_ppcm.setGeometry(QtCore.QRect(130, 150, 181, 25))
        self.r_ppcm.setObjectName("r_ppcm")
        self.r_pgcd = QtWidgets.QLineEdit(self.centralwidget)
        self.r_pgcd.setGeometry(QtCore.QRect(130, 210, 181, 25))
        self.r_pgcd.setObjectName("r_pgcd")
        self.calculer = QtWidgets.QPushButton(self.centralwidget)
        self.calculer.setGeometry(QtCore.QRect(0, 290, 501, 51))
        self.calculer.setStyleSheet("selection-color: rgb(255, 171, 1);")
        self.calculer.setObjectName("calculer")
        PPCM_PGCD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PPCM_PGCD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        PPCM_PGCD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PPCM_PGCD)
        self.statusbar.setObjectName("statusbar")
        PPCM_PGCD.setStatusBar(self.statusbar)

        self.retranslateUi(PPCM_PGCD)
        QtCore.QMetaObject.connectSlotsByName(PPCM_PGCD)

    def retranslateUi(self, PPCM_PGCD):
        _translate = QtCore.QCoreApplication.translate
        PPCM_PGCD.setWindowTitle(_translate("PPCM_PGCD", "PPCM & PGCD"))
        self.label.setText(_translate("PPCM_PGCD", "A"))
        self.label_2.setText(_translate("PPCM_PGCD", "B"))
        self.label_3.setText(_translate("PPCM_PGCD", "PPCM"))
        self.label_4.setText(_translate("PPCM_PGCD", "PGCD"))
        self.r_pgcd.setWhatsThis(_translate("PPCM_PGCD", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.calculer.setText(_translate("PPCM_PGCD", "Calculer"))

def _ppcm():
	a = ui.a.text()
	b = ui.b.text()
	
	if a.isdecimal() and b.isdecimal():
		a = int(a)
		b = int(b)
		ui.r_ppcm.setText(str(ppcm(a,b)))
		ui.r_pgcd.setText(str(pgcd(a,b)))
	else:
		ui.r_ppcm.setText("A et B Sont un nombre ")
		

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PPCM_PGCD = QtWidgets.QMainWindow()
    ui = Ui_PPCM_PGCD()
    ui.setupUi(PPCM_PGCD)
    PPCM_PGCD.show()
    
    ui.calculer.clicked.connect(lambda:_ppcm())
    
    sys.exit(app.exec_())
    
    
    
